### ISSUE TITLE
Does not work on Sierra

### ISSUE THREAD

**Issue by fpg1503** [neonichu/fastlane-ascii-art#1]
### New Issue Checklist

- [x] Updated fastlane to the latest version

### Issue Description
Every time I try to use it on Sierra I get an error when trying to build gem native extensions (rmagick).

<details><summary>🚨error output 🚨</summary>
[10:26:37]: Installing Ruby gem 'fastlane-plugin-ascii_art'...
Building native extensions.  This could take a while...
[10:26:53]: Error loading plugin 'fastlane-plugin-ascii_art': ERROR: Failed to build gem native extension.

    current directory: /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/rmagick-2.15.4/ext/RMagick
/Users/fpg1503/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170104-12438-1pma74d.rb extconf.rb
checking for /usr/bin/clang... yes
checking for Magick-config... yes
checking for outdated ImageMagick version (<= 6.4.9)... no
checking for Ruby version >= 1.8.5... yes
checking for stdint.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/fpg1503/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)
/Users/fpg1503/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
	from extconf.rb:38:in `configure_headers'
	from extconf.rb:18:in `initialize'
	from extconf.rb:517:in `new'
	from extconf.rb:517:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/rmagick-2.15.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/rmagick-2.15.4 for inspection.
Results logged to /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/rmagick-2.15.4/gem_make.out

+---------------------------+-----------+---------------------------+
|                           Used plugins                            |
+---------------------------+-----------+---------------------------+
| Plugin                    | Version   | Action                    |
+---------------------------+-----------+---------------------------+
| fastlane-plugin-cryptex   | 0.1.3     | cryptex                   |
|                           |           | cryptex_generate_keystore |
| fastlane-plugin-ascii_art | undefined | No actions found          |
+---------------------------+-----------+---------------------------+

[10:26:53]: You require a gem, if this is a third party gem, please use `fastlane_require 'digest/md5'` to ensure the gem is installed locally
[10:26:53]: -------------------------------------------------
[10:26:53]: --- Step: Verifying required fastlane version ---
[10:26:53]: -------------------------------------------------
[10:26:53]: Your fastlane version 2.4.0 matches the minimum requirement of 1.109.0  ✅
[10:26:53]: ------------------------------
[10:26:53]: --- Step: default_platform ---
[10:26:53]: ------------------------------
[10:26:53]: Driving the lane 'logo' 🚀
[10:26:53]: -------------------------------------
[10:26:53]: --- Step: ensure_git_status_clean ---
[10:26:53]: -------------------------------------
[10:26:54]: Git status is clean, all good! 💪
[10:26:54]: -------------------
[10:26:54]: --- Step: slack ---
[10:26:54]: -------------------
[10:26:54]: Successfully sent Slack notification
[10:26:54]: ----------------------------
[10:26:54]: --- Step: reset_git_repo ---
[10:26:54]: ----------------------------
[10:26:54]: $ git reset --hard HEAD
[10:26:54]: ▸ HEAD is now at 0479046 Add ascii logo
[10:26:54]: Git repo was reset and cleaned back to a pristine state.
+-----------------------------+---------+
|             Lane Context              |
+-----------------------------+---------+
| DEFAULT_PLATFORM            | android |
| PLATFORM_NAME               |         |
| LANE_NAME                   | logo    |
| GIT_REPO_WAS_CLEAN_ON_START | true    |
+-----------------------------+---------+
[10:26:54]: Plugin 'ascii_art' was not properly loaded, make sure to follow the plugin docs for troubleshooting: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/PluginsTroubleshooting.md

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | ensure_git_status_clean             | 0           |
| 4    | slack                               | 0           |
| 5    | reset_git_repo                      | 0           |
+------+-------------------------------------+-------------+

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/fpg1503/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/version.rb:207:in `initialize': Malformed version number string undefined (ArgumentError)
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/version.rb:199:in `new'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/version.rb:199:in `new'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.4.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:29:in `block in show_update_status'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.4.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `each'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.4.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `show_update_status'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.4.0/fastlane/lib/fastlane/commands_generator.rb:39:in `ensure in start'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.4.0/fastlane/lib/fastlane/commands_generator.rb:46:in `start'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.4.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Users/fpg1503/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.4.0/bin/fastlane:5:in `<top (required)>'
	from /Users/fpg1503/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/fpg1503/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.109.0"
default_platform :android

require 'digest/md5'

def ascii_logo
  md5 = Digest::MD5.hexdigest('fpg1503@gmail.com')
  gravatar = "https://www.gravatar.com/avatar/#{md5}?s=400"
  ascii_art(image_path: gravatar)
end

lane :logo do
  ascii_logo
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.4.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version   | Update-Status  |
| ------------------------- | --------- | -------------- |
| fastlane-plugin-cryptex   | 0.1.3     | ✅ Up-To-Date   |
| fastlane-plugin-ascii_art | undefined | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.2        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| fastlane-plugin-cryptex   | 0.1.3        |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.4        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.12       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.2        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-01-04**
</details>

(I've removed irrelevant portions of my Fastfile)

**Comment by KrauseFx** [comment]
Oh seems like this plugin might not work with the pre-packaged fastlane 😢

**Comment by KrauseFx** [comment]
The alternative is to install fastlane using system ruby or bundler 👍

**Comment by fpg1503** [comment]
If I try to use bundler it says that the plugin gem is missing:

```
[12:05:34]: Missing gem 'fastlane-plugin-ascii_art', please add the following to your local Gemfile:
[12:05:34]:
[12:05:34]: ▸ gem "fastlane-plugin-ascii_art"
[12:05:34]:
[12:05:34]: Error loading plugin 'fastlane-plugin-ascii_art': Add 'gem "fastlane-plugin-ascii_art"' to your Gemfile and restart fastlane
```

I ran `bundle exec fastlane logo`.

<details><summary>Gemfile</summary>

```
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source "https://rubygems.org"

gem 'fastlane'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)

```
</details>

<details><summary>Pluginfile</summary>

```
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-cryptex'
gem 'fastlane-plugin-ascii_art'

```
</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.4.0   | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                    | Version   | Update-Status  |
| ------------------------- | --------- | -------------- |
| fastlane-plugin-cryptex   | 0.1.3     | ✅ Up-To-Date   |
| fastlane-plugin-ascii_art | undefined | 💥 Check failed |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.2        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| fastlane-plugin-cryptex   | 0.1.3        |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.4        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.12       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.2        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-01-04**
</details>

**Comment by KrauseFx** [comment]
Did you run `bundle update`?

**Comment by fpg1503** [comment]
Yes 😢

**Comment by fpg1503** [comment]
The pre-packaged version of fastlane is in my path, should I remove it?

**Comment by KrauseFx** [comment]
Yes, you'll have to remove it

**Comment by fpg1503** [comment]
It did the trick! 🎉 
I got it working using fastlane with bundler, should I close this issue and open a new one(`Not working with pre-packaged fastlane`)?

**Comment by KrauseFx** [comment]
Yeah, let's close this for now 👍

**Comment by KrauseFx** [comment]
Thanks

**Comment by pangers** [comment]
Hi @fpg1503, could you outline exactly what you did to resolve this issue? 

I ran:
bundle exec fastlane add_plugin ascii_art

and got the same error as you were getting.

Then I removed fastlane from my PATH and ran 

`bundle exec fastlane add_plugin ascii_art`

and I was still getting the same error. (I'm on High Sierra)

Do you recall anything else that you had to do?

Thanks.
